name:               pomc
version:            0.1.0.0
synopsis:           A model-checking tool for POTL
description:        A model-checking tool for POTL
category:           Formal methods

author:             Davide Bergamaschi
maintainer:         davide.bergamaschi@protonmail.com

copyright:          2020 Davide Bergamaschi
license:            MIT
license-file:       COPYING.md

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:      src
  exposed-modules:
  - Pomc
  - Pomc.App
  - Pomc.Check
  - Pomc.Example
  - Pomc.Opa
  - Pomc.PotlV2
  - Pomc.Prec
  - Pomc.Prop
  - Pomc.RPotl
  ghc-options:
  - -Wall
  - -O2
  dependencies:
  - bitvec
  - containers
  - criterion-measurement
  - deepseq
  - megaparsec
  - parallel
  - parser-combinators
  - text
  - vector

executables:
  pomc:
    main:           Main.hs
    source-dirs:    app
    ghc-options:
    - -rtsopts
    - -Wall
    - -O2
    dependencies:
    - pomc

tests:
  test-pomc:
    main:           Test.hs
    source-dirs:    test
    ghc-options:
    - -rtsopts
    - -Wall
    - -O2
    dependencies:
    - pomc
    - containers
    - deepseq
    - tasty
    - tasty-hunit
    - tasty-quickcheck

benchmarks:
  bench-pomc:
    main:           Bench.hs
    source-dirs:    bench
    ghc-options:
    - -rtsopts
    - -Wall
    - -O2
    dependencies:
    - pomc
    - containers
    - criterion-measurement
